### ISSUE TITLE
Uninstalled dependency issues

### ISSUE THREAD

**Issue by phivk** [SPARQL-Anything/fx-cli-installer-mac#3]
I tested the installer and I was missing wget and a JDK.

```shell
$ ./install.sh 
[...]
“wget could not be found. Please install wget and run again.” 
```

installed via homebrew:
```
brew install wget
```

Then the install.sh worked 👍 and `fx` is now available:

```shell
$ fx 
No Java runtime present, requesting install. 
/usr/local/bin/fx: line 34: [: : integer expression expected 
No Java runtime present, requesting install. 
```

This opens a modal:
> To use the “javap” command-line tool you need to install a JDK.
> Click “More Info…” to visit the Java Developer Kit download website.

Clicking the ‘More info‘ button opens:
https://plugins.apple.com/java-en?intent=WebStart&os_version=10.15.7&jrs_version=15.0.1  
which redirects to:
https://www.adobe.com/products/flashplayer/end-of-life-alternative.html

😕

Tested on Mac OS 10.15.7

**Comment by phivk** [comment]
Installed JDK via:
```shell
brew install java
```
and symlinked it (as suggested buy homebrew):
> For the system Java wrappers to find this JDK, symlink it with
> ```
> sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
> ```

`fx` now runs as expected 🙂

**Comment by enridaga** [comment]
I think the problem here is that the installer didn't check that Java was not installed. It should stop and give feedback instead of going on with the installation.
